"""Interactive setup wizard for first-time users.

Generates an umbra.yml config file via guided prompts.
Respects Law #4 (CONTROL): everything is opt-in, nothing assumed.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

SIGNUP_URL = "https://collapseindex.org/dashboard"
CONFIG_FILENAME = "umbra.yml"

# ANSI colors (basic, works on most terminals)
BOLD = "\033[1m"
DIM = "\033[2m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"


def _prompt(label: str, default: str = "", secret: bool = False) -> str:
    """Prompt the user for input with an optional default."""
    if default:
        display = f"  {label} [{default}]: "
    else:
        display = f"  {label}: "

    try:
        if secret:
            import getpass
            val = getpass.getpass(display)
        else:
            val = input(display)
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)

    return val.strip() or default


def _yes_no(label: str, default: bool = False) -> bool:
    """Yes/no prompt."""
    suffix = "[Y/n]" if default else "[y/N]"
    val = _prompt(f"{label} {suffix}", "y" if default else "n")
    return val.lower() in ("y", "yes")


def run_setup(output_path: str | None = None) -> Path:
    """Run the interactive setup wizard. Returns path to generated config file."""
    dest = Path(output_path) if output_path else Path.cwd() / CONFIG_FILENAME

    if dest.exists():
        overwrite = _yes_no(f"{CONFIG_FILENAME} already exists. Overwrite?")
        if not overwrite:
            print("  Setup cancelled.")
            sys.exit(0)

    print()
    print(f"  {BOLD}{CYAN}umbra setup{RESET}")
    print(f"  {DIM}{'=' * 40}{RESET}")
    print()

    # -- API Key --
    print(f"  {BOLD}Step 1: CI-1T API Key{RESET}")
    print(f"  {DIM}Sign up at {SIGNUP_URL}{RESET}")
    print(f"  {DIM}Go to API Keys panel -> Create Key{RESET}")
    print()

    api_key = _prompt("API key (ci_...)", os.getenv("CI1T_API_KEY", ""))
    use_env = False
    if not api_key:
        print(f"  {YELLOW}No key provided. Set CI1T_API_KEY env var before running.{RESET}")
        use_env = True
    else:
        use_env = _yes_no("Store key in env var instead of config file? (safer)", default=True)

    # -- Policy --
    print()
    print(f"  {BOLD}Step 2: Policy Mode{RESET}")
    print(f"  {DIM}monitor = log everything, never block agents{RESET}")
    print(f"  {DIM}enforce = gate/block agents at AL3+{RESET}")
    print()
    policy = _prompt("Policy mode", "monitor")
    if policy not in ("monitor", "enforce"):
        policy = "monitor"

    # -- Port --
    print()
    port = _prompt("HTTP port", "8400")
    try:
        port_int = int(port)
    except ValueError:
        port_int = 8400

    # -- Alerts --
    print()
    print(f"  {BOLD}Step 3: Alerts (all optional){RESET}")
    print()

    slack_url = ""
    slack_channel = ""
    if _yes_no("Set up Slack alerts?"):
        slack_url = _prompt("Slack webhook URL")
        slack_channel = _prompt("Slack channel (optional)", "")

    email_cfg = {}
    if _yes_no("Set up email alerts?"):
        email_cfg["smtp_host"] = _prompt("SMTP host", "smtp.gmail.com")
        email_cfg["smtp_port"] = _prompt("SMTP port", "587")
        email_cfg["smtp_user"] = _prompt("SMTP user (email)")
        email_cfg["to"] = _prompt("Send alerts to (email)")

    sms_cfg = {}
    if _yes_no("Set up SMS alerts (Twilio)?"):
        print(f"  {DIM}Store SID/token as CI1T_TWILIO_SID and CI1T_TWILIO_TOKEN env vars{RESET}")
        sms_cfg["from"] = _prompt("From number (+1...)")
        sms_cfg["to"] = _prompt("To number (+1...)")

    # -- Build YAML --
    lines = [
        "# Umbra configuration",
        "# Generated by umbra setup",
        "",
        f"port: {port_int}",
        'host: "0.0.0.0"',
        "",
    ]

    if use_env or not api_key:
        lines.append("# Set CI1T_API_KEY env var")
        lines.append('api_key: ""')
    else:
        lines.append(f'api_key: "{api_key}"')

    lines.extend([
        'api_url: "https://collapseindex.org/api"',
        "",
        f'policy: "{policy}"',
        "episode_size: 3",
        "",
    ])

    # Alerts section
    lines.append("alerts:")
    lines.append('  min_level: "AL3"')

    if slack_url:
        lines.append("")
        lines.append("  slack:")
        lines.append(f'    webhook_url: "{slack_url}"')
        if slack_channel:
            lines.append(f'    channel: "{slack_channel}"')

    if email_cfg:
        lines.append("")
        lines.append("  email:")
        lines.append(f'    smtp_host: "{email_cfg.get("smtp_host", "")}"')
        lines.append(f'    smtp_port: {email_cfg.get("smtp_port", 587)}')
        lines.append(f'    smtp_user: "{email_cfg.get("smtp_user", "")}"')
        lines.append('    smtp_pass: ""  # Set CI1T_SMTP_PASS env var')
        lines.append(f'    from_addr: "{email_cfg.get("smtp_user", "")}"')
        lines.append("    to_addrs:")
        lines.append(f'      - "{email_cfg.get("to", "")}"')

    if sms_cfg:
        lines.append("")
        lines.append("  sms:")
        lines.append('    account_sid: ""  # Set CI1T_TWILIO_SID env var')
        lines.append('    auth_token: ""   # Set CI1T_TWILIO_TOKEN env var')
        lines.append(f'    from_number: "{sms_cfg.get("from", "")}"')
        lines.append("    to_numbers:")
        lines.append(f'      - "{sms_cfg.get("to", "")}"')

    lines.extend([
        "",
        "credits:",
        "  low_warning: 100",
        "  check_interval: 10",
        "",
    ])

    content = "\n".join(lines)
    dest.write_text(content, encoding="utf-8")

    print()
    print(f"  {GREEN}Config written to {dest}{RESET}")
    if use_env and api_key:
        print(f"  {YELLOW}Remember to set the CI1T_API_KEY environment variable.{RESET}")
    print()
    print(f"  {BOLD}Start Umbra:{RESET}")
    print("    umbra serve")
    print()

    return dest
